### ISSUE TITLE
可以用来抓室友们的密码吗

### ISSUE THREAD

**Issue by alpha-baby** [akkuman/pppoe-intercept#2]
今天突发奇想，就用wireshark来抓了下netkeeper的pppoe的包，确实可以看到自己的密码账号，就搜了下网上有没有人要就netkeeper登陆协议的，然后就看到了你的代码。如果要中间人攻击，然后可以欺骗到室友的账号密码？

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gfhs1oy9rnj30yd07nju3.jpg)

**Comment by akkuman** [comment]
同一局域网下一般是可以的，具体可以看看pppoe协议流程，最开始是广播，只要你最先回应广播就可以进行后续流程了
